### ISSUE TITLE
Did it really work for your project?

### ISSUE THREAD

**Issue by leandrodaf** [maikelmertens/aws-lambda-layer-mssql-odbc#1]
I plan to adapt this project to be used with another database, I would like to know if this actually worked as a layer for your lambdas.

**Comment by maikelmertens** [comment]
Yes it was definitely working for my projects. We have had numerous AWS Lambda's where we used this layer for connecting to a MSSQL database.

It is, however, a while ago that I've worked with these projects as I've moved to another project where we aren't making use of MSSQL databases anymore. 

Feel free to test it out!

**Comment by leandrodaf** [comment]
Cool! I will try to use it with the DBMaker database driver.
